server:
  port: 8080

spring:
  flyway:
    locations: classpath:/db/migration,classpath:/db/seeding
  datasource:
    url: jdbc://localhost:5432/aceleradora_airlines
    username: postgres
    password: airlines