server:
  port: 8080

spring:
  flyway:
    locations: classpath:/db/migration,classpath:/db/seeding
  datasource:
    url: jdbc:postgresql://localhost:5432/react_airlines
    username: postgres
    password: airlines